---
- name: Configure srv
  hosts: srv
  become: true
  tasks:
    - name: Add Kubernetes apt-key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: deb https://apt.kubernetes.io/ kubernetes-xenial main
        state: present

    - name: Install kubectl, docker-compose, and helm
      apt:
        name:
          - kubectl
          - docker-compose
        state: present

    - name: Add Helm apt key
      apt_key:
        url: https://baltocdn.com/helm/signing.asc
        state: present

    - name: Add Helm apt repository and update repository
      apt_repository:
        repo: deb https://baltocdn.com/helm/stable/debian/ all main
        state: present
        update_cache: yes

    - name: Install Helm package
      apt:
        name: helm
        state: present

    - name: Add stable Helm repository
      command: helm repo add stable https://charts.helm.sh/stable

    - name: Update Helm repositories
      command: helm repo update
